.github/workflows/build.yml
.gitignore
Makefile
internal/syncer/syncer_test.go

1. add TestRecover test for syncer module
2. modify test-coverage in makefile

test(syncer): add unit test for syncer module

---

internal/executor/executor_test.go
internal/monitor/monitor.go
internal/monitor/monitor_test.go

1. remove unused updateIndex method in monitor
2. test executor using its Start and Stop method to improve test coverage

tets(*): improve test coverage in executor and monitor

---

config/pier.toml
internal/app/pier.go
internal/repo/config.go
internal/syncer/syncer.go
internal/syncer/syncer_test.go

every wrapper received from bitxhub has to be verified in syncer module
before sending it to executor module.

feat(syncer): add verify wrapper function

---

go.mod
go.sum
internal/agent/mock_agent/mock_agent.go
internal/executor/handle.go
internal/executor/verify.go

parallelizing the applying and verifying ibtps part of executor

feat(executor): parallelizing execution of interchain tx

---

cmd/pier/appchain.go
cmd/pier/interchain.go
cmd/pier/rule.go
config/pier.toml
go.sum
internal/agent/agent.go
internal/agent/agent_test.go
internal/app/pier.go
internal/repo/config.go

add network config and direct mode config

refactor(*): refactor network config

---

cmd/pier/appchain_bxh.go
go.mod
go.sum
internal/app/pier.go
internal/exchanger/exchanger.go
internal/exchanger/handler.go
internal/exchanger/recover.go
internal/monitor/monitor.go
internal/syncer/syncer.go

test the whole interchain-invoke procedure

refactor(*): refactor modules to support direct mode

---

api/server.go
cmd/pier/client/appchain_pier.go
go.mod
go.sum
internal/app/pier.go
internal/appchain/handle.go
internal/checker/direct_checker.go
internal/exchanger/exchanger.go
internal/exchanger/handler.go
internal/lite/direct_lite/lite.go
internal/peermgr/swarm.go
internal/rulemgr/handle.go

1. appchain register to other pier with wrong id
2. appchain rule register get wrong rule contract bytes

fix(*): fix some bugs when running in direct mode

---

pkg/plugins/client/grcp.go

feat(plugins): complete replace native go plugin
complete basic grpc plugin server implementation

feat(plugins): complete replace native go plugin

---

cmd/pier/start.go
internal/app/pier.go
internal/executor/executor.go
pkg/plugins/start.go

1. plugin process won't quit after pier stopped
2. pier start plugin binary using full path

fix(plugin): fix plugin related bug

---

internal/syncer/syncer.go

syncer should appy tx in tx wrapper before persisting tx wrapper into storage

fix(syncer): fix syncer miss tx

---

internal/agent/agent_test.go
internal/monitor/monitor.go
internal/monitor/monitor_test.go

1. add test case for agent for GetPendingNonceByAccount and Get**Meta interfaces
2. add test case for monitor for handleMinssing cases

test(*): add test case for agent and monitor

---

cmd/pier/appchain_bxh.go
config/certs/ca.pem
config/pier.toml
go.mod
go.sum
internal/app/pier.go
internal/repo/config.go

1. replace new ca.pem file
2. update to latest go-bitxhub-client for issuer_name changing to common_name

chore(*): renaming and cert file changes

---

internal/executor/executor.go
internal/executor/executor_test.go
internal/executor/handle.go
internal/executor/mock_executor/mock_executor.go
pkg/plugins/grpc.go

1. remove interchain meta inside executor
2. add some error handling

refactor(executor): change code structure according to interface

---

internal/exchanger/exchanger.go
internal/exchanger/handler.go
internal/exchanger/recover.go
internal/executor/handle.go
pkg/plugins/grpc.go

1. executor ExecuteIBTP method changes the ibtp parameter
2. getCallbackMeta method in plugin returns wrong meta
3. some logger contents is not right

fix(*): fix some bugs when testing recovering from empty storage

---

internal/app/utils.go

change query type of tx to use sendView api when starting pier to solve to problem of same tx nonce for ha module.

fix(app): start with ha mode might use the same nonce

---

cmd/pier/appchain_bxh.go
cmd/pier/interchain.go
cmd/pier/rule.go
config/pier.toml
go.mod
go.sum
internal/app/pier.go
internal/repo/config.go
internal/syncer/syncer.go

add multiple bitxhub nodes config for pier in case one of these nodes is
not reachable

feat(*): add multiple bitxhub nodes config for pier

---

go.mod
go.sum

fix(go.mod): update go-bitxhub-client to fix blocking when dialing grpc

---

go.mod
go.sum
internal/agent/client.go
internal/exchanger/exchanger_test.go
internal/exchanger/handler.go
internal/exchanger/recover.go
internal/executor/executor.go
internal/executor/executor_test.go
internal/executor/handle.go
internal/executor/interface.go
internal/executor/mock_executor/mock_executor.go
internal/lite/mock_lite/mock_lite.go
internal/monitor/mock_monitor/mock_monitor.go
internal/peermgr/mock_peermgr/mock_peermgr.go
internal/repo/config.go
internal/router/mock_router/mock_router.go
internal/syncer/mock_syncer/mock_syncer.go
internal/txcrypto/mock_txcrypto/mock_txcrypto.go
pkg/plugins/grpc.go
pkg/plugins/interface.go
pkg/plugins/mock_client/mock_client.go
pkg/plugins/plugin_test.go

1. add GetReceipt to plugin interface
2. always execute callback

refactor(*): add GetReceipt to plugin interface

---

cmd/pier/appchain_bxh.go
config/pier.toml
internal/app/pier.go
internal/repo/config.go

1. remove default bitxhub node addrs
2. add timeout config

fix(*): fix blocking dial to bitxhub node with timeout

---

.github/workflows/notify.yml

ci: add notice on Dingding when there is a pr opened

---

Makefile
scripts/release_binary.sh

fix(ci):get app_version automatically

---

go.mod
go.sum
internal/app/utils.go
internal/exchanger/exchanger.go
internal/exchanger/exchanger_test.go
internal/exchanger/handler.go
internal/exchanger/recover.go
internal/syncer/agent.go
internal/syncer/interface.go
internal/syncer/mock_syncer/mock_syncer.go
internal/syncer/syncer_test.go

1. syncer handle send ibtp according to error types
2. exchanger handle re send ibtp and update meta logic

feat(*): resend ibtp according to error types

---

cmd/pier/appchain_bxh.go
cmd/pier/client/appchain_pier.go
cmd/pier/did.go
cmd/pier/governance.go
cmd/pier/pier.go
go.mod
go.sum
internal/agent/client.go
internal/app/pier.go
internal/app/utils.go
internal/exchanger/exchanger_test.go
internal/router/mock_router/mock_router.go
internal/router/router.go
internal/router/router_test.go
internal/router/union_router.go
internal/syncer/agent.go
internal/syncer/interface.go
internal/syncer/mock_syncer/mock_syncer.go
internal/syncer/syncer_test.go

1. Improve some command parameters for appchain governance;
2. Add a command to withdraw the proposal;
3. Change the appchain used to the appchain in the bitxhub-model to facilitate unified modification.

feat(cmd): adapt to appchain management

---

.dockerignore
.github/workflows/release.yml
Dockerfile-pier
scripts/docker_entrypoint.sh
scripts/release_binary.sh

1. add auto release docker image scripts
2. modify the release package naming format

ci(*):add auto release docker image scripts

---

cmd/pier/appchain_bxh.go
cmd/pier/did.go
cmd/pier/rule.go
internal/executor/mock_executor/mock_executor.go
internal/lite/mock_lite/mock_lite.go
internal/monitor/mock_monitor/mock_monitor.go
internal/peermgr/mock_peermgr/mock_peermgr.go
internal/router/mock_router/mock_router.go
internal/syncer/mock_syncer/mock_syncer.go
internal/txcrypto/mock_txcrypto/mock_txcrypto.go
pkg/plugins/mock_client/mock_client.go

1. Add validation rule register
2. Add default validation rules to the application chain of type Fabric

feat(*): improve rule governance

---

cmd/pier/did.go
cmd/pier/rule.go

1. Delete the interface which to freeze rule, active rule, bind rule, unbind rule
2. Fix the bug that did not apply the chain public key when registering to bitxhub

feat(cmd): simplify validation rule management

---

.github/workflows/release.yml
Dockerfile-pier

update release.yml and dockerfile

update release.yml and dockerfile

---

cmd/pier/appchain_bxh.go
cmd/pier/did.go
cmd/pier/flags.go
cmd/pier/governance.go
cmd/pier/rule.go

1. Add governance reason;
2. Add friendlier hints for freezing and activating operations that do not return proposal numbers.

fix(*): add governance reason

---

cmd/pier/appchain_bxh.go
cmd/pier/flags.go
cmd/pier/service.go
internal/syncer/utils.go

1. fix the return type of GetServicesByAppchainID
2. add option to specify bitxhub node address when registering appchain

Fix: get service and registering appchain

---

internal/adapt/bxh_adapter/adapter.go
internal/adapt/bxh_adapter/adapter_test.go
internal/adapt/bxh_adapter/utils.go
internal/adapt/err.go

- Comment redundant code(target err from bxh).

fix(bxhAdapter): handle some error code

---

config/pier.toml
go.sum
internal/exchanger/exchanger.go
internal/repo/config.go

1. Change "toml" to "mapstructure" to fix the bug that the tss configuration does not take effect;
2. Change the TSS configuration item to the default false.

fix(*): fix invalid tss configuration

---

internal/exchanger/exchanger_test.go

replenish_uint_test

---

go.mod
go.sum
internal/adapt/appchain_adapter/adapter.go
internal/adapt/appchain_adapter/adapter_test.go
internal/adapt/bxh_adapter/adapter.go
internal/adapt/bxh_adapter/utils.go
internal/exchanger/exchanger.go
internal/exchanger/recover.go

fix: handle rollback for one to multi
fix: appchain adapter submitReceipt when receiving  interchain(need rollback)

feat: adapt one to multi IBTP
